services:
  - type: web
    name: pharmasupply-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: node Server.js
    healthCheckPath: /health
    envVars:
      - key: MONGODB_URI
        sync: false # Should be set in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: LOG_LEVEL
        value: info
      - key: BLOCKCHAIN_RPC_URL
        value: https://pharmasupply-hardhat.onrender.com
      - key: DEV_PRIVATE_KEY
        value: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

  - type: web
    name: pharmasupply-hardhat
    env: node
    plan: free
    region: oregon
    rootDir: web3
    buildCommand: npm install
    startCommand: npx hardhat node --hostname 0.0.0.0
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8545
